## **Types of Naive Bayes Classifiers**

### **Topic Roadmap**

**1. Global Configuration and Imports**

**2. Gaussian Naive Bayes (Continuous Data)**

**3. Multinomial Naive Bayes (Count Data)**

**4. Bernoulli Naive Bayes (Binary Data)**

**5. Categorical Naive Bayes (Discrete Categories)**

**6. Poisson Naive Bayes (Event Frequency Data)**

### **1. Global Configuration and Imports**

Import necessary libraries and standard Naive Bayes models available in Scikit-Learn.

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_classification

from sklearn.naive_bayes import (
    GaussianNB,
    MultinomialNB,
    BernoulliNB,
    CategoricalNB
)

### **2. Gaussian Naive Bayes**

Assumes continuous features follow a normal (Gaussian) distribution.
$$P(x_i | y) = \frac{1}{\sqrt{2\pi\sigma_y^2}} \exp\left(-\frac{(x_i - \mu_y)^2}{2\sigma_y^2}\right)$$

In [2]:
# Dataset Loading / Generation
X_gauss, y_gauss = make_classification(n_samples=500, n_features=4, random_state=42)
X_train_g, X_test_g, y_train_g, y_test_g = train_test_split(X_gauss, y_gauss, test_size=0.2, random_state=42)

In [3]:
# Model Training and Evaluation
gnb = GaussianNB()
gnb.fit(X_train_g, y_train_g)

gnb_preds = gnb.predict(X_test_g)
print(f"Gaussian NB Accuracy: {accuracy_score(y_test_g, gnb_preds):.4f}")

Gaussian NB Accuracy: 0.8800


### **3. Multinomial Naive Bayes**

Used for discrete counts. It is widely used in text classification where features are term frequencies or TF-IDF vectors.

In [4]:
# Dataset Generation: Random integer counts (e.g., word frequencies)
np.random.seed(42)
X_multi = np.random.randint(0, 10, size=(500, 5))
y_multi = np.random.randint(0, 2, size=500)

X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(X_multi, y_multi, test_size=0.2, random_state=42)

In [5]:
# Model Training and Evaluation
mnb = MultinomialNB()
mnb.fit(X_train_m, y_train_m)

mnb_preds = mnb.predict(X_test_m)
print(f"Multinomial NB Accuracy: {accuracy_score(y_test_m, mnb_preds):.4f}")

Multinomial NB Accuracy: 0.4700


### **4. Bernoulli Naive Bayes**

Designed for binary/boolean features. If a feature is not binary, `BernoulliNB` can binarize it using a threshold.

In [6]:
# Dataset Generation: Random binary features (0 or 1)
X_bern = np.random.randint(0, 2, size=(500, 5))
y_bern = np.random.randint(0, 2, size=500)

X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(X_bern, y_bern, test_size=0.2, random_state=42)

In [7]:
# Model Training and Evaluation
bnb = BernoulliNB()
bnb.fit(X_train_b, y_train_b)

bnb_preds = bnb.predict(X_test_b)
print(f"Bernoulli NB Accuracy: {accuracy_score(y_test_b, bnb_preds):.4f}")

Bernoulli NB Accuracy: 0.4500


### **5. Categorical Naive Bayes**

Suitable for classification with discrete categorical features. It assumes that each feature has its own categorical distribution.

In [8]:
# Dataset Generation: Random categories (e.g., 0, 1, 2 representing Red, Green, Blue)
X_cat = np.random.randint(0, 3, size=(500, 4))
y_cat = np.random.randint(0, 2, size=500)

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X_cat, y_cat, test_size=0.2, random_state=42)

In [9]:
# Model Training and Evaluation
cnb = CategoricalNB()
cnb.fit(X_train_c, y_train_c)

cnb_preds = cnb.predict(X_test_c)
print(f"Categorical NB Accuracy: {accuracy_score(y_test_c, cnb_preds):.4f}")

Categorical NB Accuracy: 0.6200


### **6. Poisson Naive Bayes**

Used when features represent event frequencies over a fixed interval (e.g., number of website clicks per hour, calls received per day).

**Mathematical Concept:**
It assumes the data is generated from a Poisson distribution:
$$P(x_i | y) = \frac{\lambda_y^{x_i} e^{-\lambda_y}}{x_i!}$$

*Note: Scikit-Learn does not provide a native `PoissonNB` class. In practice, researchers handle count data using MultinomialNB or build custom implementations. Below is data generated following a Poisson distribution to demonstrate how the inputs are structured.*

In [10]:
# Dataset Generation: Poisson distributed count data
# lambda (lam) represents the expected number of events occurring in a fixed time interval.
X_poisson_class0 = np.random.poisson(lam=2, size=(250, 3)) 
X_poisson_class1 = np.random.poisson(lam=8, size=(250, 3))

X_poisson = np.vstack((X_poisson_class0, X_poisson_class1))
y_poisson = np.hstack((np.zeros(250), np.ones(250)))

# Display sample rows representing event counts
print("Sample Poisson Features:\n", X_poisson[:5])

Sample Poisson Features:
 [[1 4 5]
 [1 2 3]
 [3 2 0]
 [0 0 3]
 [1 5 2]]


### **Key Revision Notes**

- **Gaussian NB:** Default choice for continuous numerical data (e.g., height, weight, financial values).
- **Multinomial NB:** Standard for term frequencies, word counts, and text processing pipelines.
- **Bernoulli NB:** Strictly for boolean/binary features (e.g., word presence vs. absence). 
- **Categorical NB:** Designed for features mapping to discrete categories (e.g., blood type, car model). Inputs must be ordinally encoded.
- **Poisson NB:** Theoretical framework for specific event-count data occurring over time or space.