## **Principal Component Analysis (PCA) - Part 1: Mathematical Foundation**

### Topic Roadmap

**1. Introduction to PCA**

**2. Imports & Data Generation**

**3. Step 1: Mean Centering & Standard Scaling**

**4. Step 2: The Covariance Matrix**

**5. Step 3: Eigenvalues and Eigenvectors**

**6. Key Revision Notes**

### **1. Introduction to PCA**

Principal Component Analysis (PCA) is an unsupervised dimensionality reduction technique. It transforms a dataset into a new coordinate system where the axes (Principal Components) represent the directions of maximum variance

In Part 1, we will generate 3D data and compute the mathematical prerequisites for PCA: the Covariance Matrix and Eigen Decomposition.

### **2. Imports & Data Generation**

We will generate a synthetic 3D dataset composed of two distinct classes using a multivariate normal distribution

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

np.random.seed(23)

In [2]:
# Generate Class 1 samples
mu_vec1 = np.array([0, 0, 0])
cov_mat1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df_class1 = pd.DataFrame(class1_sample, columns=['feature1', 'feature2', 'feature3'])
df_class1['target'] = 1

In [3]:
# Generate Class 2 samples
mu_vec2 = np.array([1, 1, 1])
cov_mat2 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df_class2 = pd.DataFrame(class2_sample, columns=['feature1', 'feature2', 'feature3'])
df_class2['target'] = 0

In [4]:
# Combine and shuffle the dataset
df = pd.concat([df_class1, df_class2], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
df.head()

,feature1,feature2,feature3,target
0,-0.992574,-0.161346,1.192404,1
1,-0.420844,-0.551989,-0.121098,1
2,-0.045438,1.040886,-0.094035,1
3,0.898907,0.435960,0.820964,0
4,0.322272,0.060343,-1.043450,1


### **3. Step 1: Mean Centering & Standard Scaling**

PCA is highly sensitive to the scale of the features. We must center the data (mean = 0) and scale it to unit variance (standard deviation = 1) before calculating the covariance matrix

In [5]:
# Isolate features
feature_cols = ['feature1', 'feature2', 'feature3']
X = df[feature_cols].copy()

In [6]:
# Apply standard scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Scaled data mean (approx 0):", np.mean(X_scaled, axis=0))
print("Scaled data std (approx 1):", np.std(X_scaled, axis=0))

Scaled data mean (approx 0): [-6.38378239e-17  2.77555756e-17 -2.22044605e-17]
Scaled data std (approx 1): [1. 1. 1.]


### **4. Step 2: The Covariance Matrix**

The covariance matrix captures how each feature varies with every other feature. Because our data is standardized, the covariance matrix is equivalent to the correlation matrix

In [7]:
# Compute the covariance matrix. 
# Note: np.cov expects variables as rows, so we transpose X_scaled.
covariance_matrix = np.cov(X_scaled.T)
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


### **5. Step 3: Eigenvalues and Eigenvectors**

Eigenvectors represent the directions of the new feature space (Principal Components), and eigenvalues represent the magnitude of variance captured in those directions

In [8]:
# Compute Eigenvalues and Eigenvectors
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [9]:
print("Eigenvalues:\n", eigen_values)
print("\nEigenvectors (Columns):\n", eigen_vectors)

Eigenvalues:
 [1.3536065  0.94557084 0.77774573]

Eigenvectors (Columns):
 [[-0.53875915 -0.69363291  0.47813384]
 [-0.65608325 -0.01057596 -0.75461442]
 [-0.52848211  0.72025103  0.44938304]]


### **6. Key Revision Notes**

- **Scaling is Mandatory:** PCA relies on variance. If features are on different scales, features with larger ranges will disproportionately dominate the Principal Components.
- **Covariance Matrix:** A square, symmetric matrix that describes the linear relationships between all pairs of features.
- **Eigenvectors:** The direction of the principal components. In `numpy.linalg.eig`, these are returned as **columns**, not rows.
- **Eigenvalues:** Scalar values denoting the amount of variance explained by their corresponding eigenvector.